################################################
## << Mastring Python -- Elzero Web School >> ##
#########    WEEK #09.0 Assignments    #########
## ----------- From #065  to #068 ----------- ##
print("############ Starting ############\n") ##
################################################




#######################################
#        <<<<< task #01 >>>>>        ##
print("\n<<<<< task #01 >>>>>")      ##
#######################################
import os  # used all over the tasks

# creating the Python directory in the Desktop
if os.path.exists(r"C:\Users\TALAL\Desktop\Python"):
    pass
else:
    os.makedirs(r"C:\Users\TALAL\Desktop\Python")

# creating the file assign.py
file1 = open(r"C:\Users\TALAL\Desktop\Python\assign.py", "w")
print(os.path.abspath(__file__)) 
file1.close()

# creating the 50 txt files
for i in range(1,51):
    s = str(i)
    if s != "25":
        file2 = open(r"C:\Users\TALAL\Desktop\Python\txt{}.txt".format(s.zfill(2)),"w")
        file2.write(f"Elzero Web School => {s}")
        file2.close()
    else:
        file2 = open(r"C:\Users\TALAL\Desktop\Python\special-text.txt","w")
        file2.close()
    i += 1

# printing the the details lines
print(os.getcwd()) # line one
print(os.path.abspath(file1.name)) # line two
print(os.path.basename(file1.name)) # line three
print(len(os.listdir(r"C:\Users\TALAL\Desktop\Python"))) #line four
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>



#######################################
#        <<<<< task #02 >>>>>        ##
print("\n<<<<< task #02 >>>>>")      ##
#######################################  
file_txt01 = open(r"C:\Users\TALAL\Desktop\Python\txt01.txt", "a")
file_txt01.write(50 * "\nAppended => Elzero Web School")

# OR (remove commenting of the for loop)

# for i in range(0,50):
#     file_txt01.write("\nAppended => Elzero Web School")
#     i += 1
file_txt01.close()
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>



#######################################
#        <<<<< task #03 >>>>>        ##
print("\n<<<<< task #03 >>>>>")      ##
####################################### 
# # This answer is generated by Bing AI chat
file_txt01 = r"C:\Users\TALAL\Desktop\Python\txt01.txt"
with open(file_txt01, "r") as f:
    lines = f.readlines()
    line_count = len(lines)
    word_count = sum(len(line.split()) for line in lines)
    char_count = sum(len(line) for line in lines)
    l_count = sum(line.count("l") for line in lines)

print(f"Number of lines: {line_count}")
print(f"Number of words: {word_count}")
print(f"Number of characters: {char_count}")
print(f"Number of 'l' characters: {l_count}")
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>



#######################################
#        <<<<< task #04 >>>>>        ##
print("\n<<<<< task #04 >>>>>")      ##
####################################### 
print("removing last 10 files")
for r in range(41, 51):
    os.remove(r"C:\Users\TALAL\Desktop\Python\txt{}.txt".format(r))
    r += 1
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>




###############################################
###############################################
print("\n############# Finished #############")